# Generated by Django 5.2.10 on 2026-01-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('finished', models.IntegerField(default=0)),
                ('session_id', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('session_data', models.JSONField(default=dict)),
                ('flag', models.TextField(blank=True, default='')),
                ('time', models.IntegerField(default=0)),
                ('survey', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
