# Generated by Django 5.2.10 on 2026-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_linebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
