# Generated by Django 5.2.10 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling_linebot", "0002_replytoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="replytoken",
            name="user_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
