# Generated by Django 5.2.10 on 2026-02-21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling_linebot", "0003_replytoken_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="risk_level",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
