# Generated by Django 5.2.10 on 2026-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_linebot', '0004_session_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='risk_level_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
